Development
Prasanthkota165/Group_H_SUDOKU-GENERATOR pull request #14
Opened 2020-06-01 00:25 UTC by rishithrao57

Review the code and suggest any changes. The code cannot detect any characters or symbols. So please avoid using them. I tried a lot of methods to solve this issue and I need some time to test it for more types of inputs. It will be resolved before release 2.

2020-06-01 00:59 UTC, gabriels2018 approved these changes
it is fine
your function definition at .h need to be updated

2020-06-01 01:01 UTC, Prasanthkota165 approved these changes
Looks good to me. But, the character as a input could be done in the Release 2 in the Rishith's changes.

2020-06-01 01:01 UTC, rishithrao57 commented
Ok will do it.

2020-06-01 01:33 UTC, Mathieufalardeau3 requested changes
I have made my reviews of the input_sudoku.c file. In summary, it does not need so much empty space. Please take a look at my comments.

2020-06-01 01:33 UTC, Mathieufalardeau3 commented on src/generate_sudoku_template.c
> +*File name: generate_sudoku_templete.c
The file name is misspelled.
The name should be : general_sudoku_template.c

2020-06-01 01:33 UTC, Mathieufalardeau3 commented on src/generate_sudoku_template.c
> +void generate_sudoku_templete(int sudoku_temp[][9]){
The function name is misspelled.
The name should be : general_sudoku_templ**a**te(...)

2020-06-01 01:33 UTC, Mathieufalardeau3 commented on src/input_sudoku.c
> +
Keep the code tight. Reduce the number of empty empty lines.

2020-06-01 01:33 UTC, Mathieufalardeau3 commented on src/input_sudoku.c
> +
Keep the code tight. Reduce the number of empty empty lines.

2020-06-01 01:33 UTC, Mathieufalardeau3 commented on src/input_sudoku.c
> +    if (diff_level != 0 && diff_level !=1 && diff_level !=2 && diff_level !=3)
Stay consistent with the bracket position: it should look like this:
if{
...
}

2020-06-01 01:33 UTC, Mathieufalardeau3 commented on src/input_sudoku.c
> +  while(2)
Same thing again for the bracket position. Keep the code tight:
while(2){
...
}

2020-06-01 01:33 UTC, Mathieufalardeau3 commented on src/input_sudoku.c
> +}}
Why is there two brackets at the end? There should only be one. 

Also remember to include **return;** at the end to avoid any ambiguity.

2020-06-01 01:33 UTC, Mathieufalardeau3 commented on src/input_sudoku.c
> +{
Why are there two brackets? There should only be one.

2020-06-01 01:41 UTC, rishithrao57 commented
Ok will do these changes and will update it by tomorrow.

2020-06-01 02:04 UTC, Prasanthkota165 commented
Since, this pull request is open under development branch. Mine and Gabriel changes came under this pull request. I request to review it both.

2020-06-01 04:05 UTC, Mathieufalardeau3 requested changes
Overall, couple of corrections needed for the code structure. 
-There should be only one header file;
-The number of character per line should less than 80;
-  The variables needs to be declared at the top of the function

2020-06-01 04:05 UTC, Mathieufalardeau3 commented on src/rearrange_cols_rows.c
> +int main(void){
The main() needs to be removed. This file should only have functions.

2020-06-01 04:05 UTC, Mathieufalardeau3 commented on src/rearrange_cols_rows.c
> +void rearrange_cols_rows(int sudoku_template[][9], int rearranged_sudoku[][9]){
Where are your code comments?

2020-06-01 04:05 UTC, Mathieufalardeau3 commented on src/rearrange_cols_rows.c
> +  int b_1[9][3];
Your variables should not be declared here. They should be declared at the top of the function.

2020-06-01 04:05 UTC, Mathieufalardeau3 commented on src/rearrange_cols_rows.c
> +int choose_number(int rangeLow, int rangeHigh) {
Where are your comments?

2020-06-01 04:05 UTC, Mathieufalardeau3 commented on src/rearrange_cols_rows.c
> +  int i,j;
Your variables should not be there.

2020-06-01 04:05 UTC, Mathieufalardeau3 commented on src/rearrange_cols_rows.c
> +
Where are your code comments?

2020-06-01 04:05 UTC, Mathieufalardeau3 commented on src/rearrange_cols_rows.c
> +void change_columns(int col_matrix[][9], int p, int q, int r){
Where are your code comments?

2020-06-01 04:05 UTC, Mathieufalardeau3 commented on src/rearrange_cols_rows.c
> +void change_rows(int row_matrix[][9], int x, int y, int z){
Where are your code comments?

2020-06-01 04:05 UTC, Mathieufalardeau3 commented on src/rearrange_cols_rows.c
> +
Keep your brackets tight

2020-06-01 04:05 UTC, Mathieufalardeau3 commented on src/rearrange_cols_rows.c
> +  int i,j;
Where are your code comments?

2020-06-01 04:05 UTC, Mathieufalardeau3 commented on src/rearrange_cols_rows.c
> +void row_groups(int r_group[][9], int c_1[3][9], int c_2[3][9], int c_3[3][9]){
Where are your code comments?

2020-06-01 04:05 UTC, Mathieufalardeau3 commented on src/apply_mask.c
> +* Numbers are masked from the rearranged 2D array locations based on diffculty level. The difficulty levels are catagorized as easy, medium, hard,
Remember that the max number of characters per line is 80. Your comments are too long per line. The teacher should not need to scroll to the right to read our comments.

2020-06-01 04:05 UTC, Mathieufalardeau3 commented on src/apply_mask.c
> +/**
This portion should be in the sudoku.h file.

2020-06-01 04:05 UTC, Mathieufalardeau3 commented on include/rearrange_cols_rows.h
> + * @file rearrange_cols_rows.h
This rearrange_cols_rows.h content should be in sudoku.h. We've discussed that we would have multiple files, but only one header file. Transfer the content of this file to header.h.

2020-06-01 16:15 UTC, Prasanthkota165 commented on include/rearrange_cols_rows.h
> + * @file rearrange_cols_rows.h
I merged this rearrange_cols_rows.h into the sudoku.h file.

2020-06-01 16:15 UTC, Prasanthkota165 commented on src/rearrange_cols_rows.c
> +void row_groups(int r_group[][9], int c_1[3][9], int c_2[3][9], int c_3[3][9]){
Mentioned the comments now.

2020-06-01 16:15 UTC, Prasanthkota165 commented on src/rearrange_cols_rows.c
> +  int i,j;
Mentioned the comments now.

2020-06-01 16:15 UTC, Prasanthkota165 commented on src/rearrange_cols_rows.c
> +void change_columns(int col_matrix[][9], int p, int q, int r){
Mentioned the comments now.

2020-06-01 16:15 UTC, Prasanthkota165 commented on src/rearrange_cols_rows.c
> +
Mentioned the comments now.

2020-06-01 16:16 UTC, Prasanthkota165 commented on src/rearrange_cols_rows.c
> +int choose_number(int rangeLow, int rangeHigh) {
Mentioned the comments now.

2020-06-01 16:17 UTC, Prasanthkota165 commented on src/rearrange_cols_rows.c
> +  int b_1[9][3];
These variables are for the inside function purpose. It would be safe to be a local variables in the function itself.

2020-06-01 16:17 UTC, Prasanthkota165 commented on src/rearrange_cols_rows.c
> +int main(void){
Removed. The function is ready for testing.

2020-06-01 16:23 UTC, Mathieufalardeau3 commented on src/rearrange_cols_rows.c
> +  int b_1[9][3];
What I meant to say is that you are declaring variables at two different locations: before and after you call the functions. All variable declaration should be written before the functions are called.

2020-06-01 16:33 UTC, Prasanthkota165 commented on src/rearrange_cols_rows.c
> +  int b_1[9][3];
I hope this clarify everything. Thanks

2020-06-02 01:06 UTC, Mathieufalardeau3 approved these changes

2020-06-03 18:57 UTC, merged