Release Issues
Prasanthkota165/Group_H_SUDOKU-GENERATOR pull request #18
Opened 2020-06-06 18:59 UTC by Prasanthkota165

Solving Github issues

2020-06-06 19:01 UTC, rishithrao57 approved these changes

2020-06-06 19:02 UTC, gabriels2018 approved these changes
I approve merging these changes

2020-06-06 19:03 UTC, Mathieufalardeau3 requested changes

2020-06-06 19:03 UTC, Mathieufalardeau3 commented on include/sudoku.h
> +static inline void ClearInputBuffer();
The functions should be named with lower case letters and spaces. The prof will deduct points for wrong standard.

2020-06-06 19:03 UTC, Mathieufalardeau3 commented on include/sudoku.h
> +void getIntegerFromStdin(int *inputInteger);
The functions should be named with lower case letters and spaces. The prof will deduct points for wrong standard.

2020-06-06 19:03 UTC, Mathieufalardeau3 commented on src/input_sudoku.c
> +void getIntegerFromStdin(int *inputInteger){
The functions and variables should be named with lower case letters and spaces. The prof will deduct points for wrong standard.

2020-06-07 01:21 UTC, Mathieufalardeau3 approved these changes

2020-06-07 16:50 UTC, Prasanthkota165 commented
Looks good to me. Shall I merge it?

2020-06-07 16:56 UTC, rishithrao57 commented
Yes, do it.

2020-06-07 18:29 UTC, merged