Sudoku solver merge
Prasanthkota165/Group_H_SUDOKU-GENERATOR pull request #21
Opened 2020-06-15 18:39 UTC by Mathieufalardeau3

2020-06-15 19:37 UTC, gabriels2018 approved these changes
I approve the merge request

2020-06-16 19:58 UTC, Mathieufalardeau3 commented on test/src/solver_sudoku_test.c
> + _Bool sortArray_and_test(int tester[ROWS]){
Make sure to follow the naming convention.

2020-06-16 20:40 UTC, Prasanthkota165 requested changes
Can you guys do this explanation in SUDOKU.H?

2020-06-16 20:42 UTC, Prasanthkota165 commented on src/solver_sudoku.c
> + */
This part.

2020-06-16 20:42 UTC, Prasanthkota165 commented on src/solver_sudoku.c
> + */
Can you include in SUDOKU.H?

2020-06-16 20:49 UTC, rishithrao57 approved these changes
Looks good.

2020-06-16 20:49 UTC, Prasanthkota165 approved these changes

2020-06-16 20:50 UTC, gabriels2018 approved these changes
I approve the merge to development

2020-06-16 20:50 UTC, merged